version: '2'
services:
    universitymailing-app:
        image: universitymailing
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://universitymailing-mysql:3306/universitymailing?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    universitymailing-mysql:
        extends:
            file: mysql.yml
            service: universitymailing-mysql
